# Generated by Django 3.1.2 on 2020-10-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20201028_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoc', models.BooleanField(default=False)),
                ('leader', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('leaders', models.ManyToManyField(related_name='_modulestack_leaders_+', through='managers.ModuleLeaders', to='managers.StakeHolder')),
                ('module_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModuleStack-ModuleType+', to='managers.moduletype')),
                ('parent_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModuleStack-Module+', to='managers.modulestack')),
            ],
        ),
        migrations.AddField(
            model_name='moduleleaders',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leaders-Module+', to='managers.modulestack'),
        ),
        migrations.AddField(
            model_name='moduleleaders',
            name='stakeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leader-StakeHolder+', to='managers.stakeholder'),
        ),
        migrations.CreateModel(
            name='LeaderModuleChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('new_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaderModuleChangeHistory-Module-new_module+', to='managers.modulestack')),
                ('old_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaderModuleChangeHistory-Module-old_module+', to='managers.modulestack')),
                ('stakeholder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaderModuleChangeHistory-StakeHolder+', to='managers.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderManagerChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('new_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaderManagerChangeHistory-StakeHolder-new_manager+', to='managers.stakeholder')),
                ('old_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaderManagerChangeHistory-StakeHolder-old_manger+', to='managers.stakeholder')),
                ('stakeholder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaderManagerChangeHistory-StakeHolder-stakeholder+', to='managers.stakeholder')),
            ],
        ),
    ]
