# Generated by Django 3.1.2 on 2020-10-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_auto_20201028_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroups',
            name='parent',
        ),
    ]
