# Generated by Django 3.1.2 on 2020-10-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_remove_permissiongroups_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulestack',
            name='parent_module',
        ),
    ]
