# Generated by Django 3.1.2 on 2020-10-29 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0007_remove_modulestack_parent_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StakeHolder-manager-StakeHolder+', to=settings.AUTH_USER_MODEL),
        ),
    ]
