# Generated by Django 3.1.2 on 2020-10-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_auto_20201028_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StakeHolder-manager-StakeHolder+', to='managers.stakeholder'),
        ),
    ]
