# Generated by Django 3.1.2 on 2020-10-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_auto_20201029_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='manager',
        ),
    ]
