# Generated by Django 3.1.2 on 2020-10-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0010_remove_stakeholder_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StakeHolder-manager-StakeHolder+', to='managers.stakeholder'),
        ),
    ]
