# Generated by Django 3.1.2 on 2020-11-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0016_modulestack_parent_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='enum',
            field=models.IntegerField(choices=[(0, 'STACK'), (1, 'GROUP_MODULE'), (2, 'MODULE'), (3, 'WORK_MODULE')], null=True),
        ),
    ]
